/// Maps TMDB keyword ids → extra genre names to union into a title's
/// `genres` set.
///
/// The problem this solves: genre filtering on Home + Decide is an AND
/// intersection (`selected.every(r.genres.contains)`). TMDB's canonical
/// genre taxonomy is narrow — e.g. "Firefly" is tagged `Sci-Fi & Fantasy`
/// only, not `Western`, so a Western + Sci-Fi filter drops it. TMDB's
/// keyword taxonomy is much richer (thousands of tags), so a keyword like
/// "space western" is a reliable signal that a title also deserves the
/// `Western` tag for intersection purposes.
///
/// **Scope**: this is additive only. We never remove canonical genres based
/// on keywords — a title that's canonically a Comedy stays a Comedy even
/// if a keyword says otherwise. The map only widens.
///
/// **Populating the map**: TMDB keyword ids are stable but not publicly
/// documented in bulk. Use `scripts/generate_keyword_genre_map.py` to look
/// up ids by name and emit entries. Each entry should be a keyword that
/// implies ≥1 canonical genre with high confidence (e.g. "cyberpunk" →
/// Science Fiction is safe; "based on novel" → no genre implication and
/// should NOT be in the map).
///
/// Keys are TMDB keyword ids; values are sets of canonical genre names
/// matching those in `utils/tmdb_genres.dart`. Unknown genre names are
/// harmless — `augmentGenresWithKeywords` just unions them in.
/// Bump when [kKeywordToExtraGenres] OR [kKeywordToSubgenres] gains meaningful
/// new entries that should re-augment previously-fetched rec docs. Rec docs
/// store the version that was live when they were last augmented; the service
/// re-fetches keywords (and re-runs augmentation for BOTH genres + sub-genres)
/// whenever the stored version is older than this.
///
/// Single version covers both axes — the same `/keywords` fetch feeds both
/// maps, so one stamp per doc keeps the backfill walk simple.
///
/// v4 (2026-05-23): expanded sub-genre map from ~16 to ~70 tags across all
/// major canonical genres, added [kSubgenreParents] for contextual
/// visibility, fixed pre-generator anime keyword id (10084 was "rescue";
/// real anime id is 210024).
const int kKeywordsVersion = 4;

const Map<int, Set<String>> kKeywordToExtraGenres = <int, Set<String>>{
  // ---- seed entries (pre-generator, kept for sanity / back-compat) ----
  9951: {'Science Fiction'}, // alien
  4458: {'Science Fiction'}, // post-apocalyptic future
  4565: {'Science Fiction'}, // dystopia
  210024: {'Animation'}, // anime (verified id; old 10084 was "rescue")
  9715: {'Action'}, // superhero
  // 1721 "fight" — intentionally NOT here; too broad, would over-tag dramas.

  // ---- generated by scripts/generate_keyword_genre_map.py ----
  // Cross-genre sci-fi/war (the Sci-Fi + War zero-result problem).
  1826: {'Science Fiction', 'War'}, // space marine
  14909: {'Science Fiction', 'War'}, // alien invasion
  2902: {'Science Fiction', 'War'}, // space battle
  161176: {'Science Fiction'}, // space opera
  // Western crossovers.
  11606: {'Science Fiction', 'Western'}, // space western
  168713: {'Western'}, // neo-western
  // Horror subgenres.
  12339: {'Horror'}, // slasher
  163053: {'Horror'}, // found footage
  215959: {'Horror', 'Science Fiction'}, // cosmic horror
  283085: {'Horror'}, // body horror
  295907: {'Horror'}, // psychological horror
  12377: {'Horror'}, // zombie
  3133: {'Horror'}, // vampire
  161791: {'Science Fiction'}, // kaiju
  // Crime/Mystery crossovers.
  207268: {'Crime', 'Mystery'}, // neo-noir
  10051: {'Crime'}, // heist
  10714: {'Crime', 'Thriller'}, // serial killer
  // Sci-fi flavours.
  12190: {'Science Fiction'}, // cyberpunk
  4379: {'Science Fiction'}, // time travel
  371846: {'Science Fiction'}, // artificial intelligence
  4563: {'Science Fiction'}, // virtual reality
  // Action flavours.
  779: {'Action'}, // martial arts
  780: {'Action'}, // kung fu
  // Musical.
  4344: {'Music'}, // musical
  // Horror TV-pickup keywords — TMDB has no TV Horror genre id, so when
  // these keywords get pulled into the pool via kGenreBoostKeywords['Horror']
  // the augmenter has to STAMP "Horror" on the resulting rec docs or the
  // client-side AND filter will drop them. Without this, picking just
  // Horror surfaces ~7 movies and zero TV (the v0.10.3 sparse-Horror fix).
  6152: {'Horror'}, // supernatural
  33505: {'Horror'}, // gothic
  2626: {'Horror'}, // exorcism
  161261: {'Horror'}, // demonic possession
  616: {'Horror'}, // witch (kept conservative — 616 is the "witch" tag, not generic occult)
  40931: {'Horror'}, // witchcraft
};

/// Returns a genre list combining [currentGenres] with any extras implied
/// by [keywordIds] per [kKeywordToExtraGenres]. Order is preserved
/// (existing genres first, then new ones in keyword-iteration order) and
/// duplicates are dropped.
///
/// Unknown keyword ids are silently skipped — TMDB adds new keywords
/// regularly and we only care about the subset we've mapped.
List<String> augmentGenresWithKeywords(
  Iterable<String> currentGenres,
  Iterable<int> keywordIds,
) {
  final seen = <String>{};
  final out = <String>[];
  for (final g in currentGenres) {
    if (g.isEmpty) continue;
    if (seen.add(g)) out.add(g);
  }
  for (final id in keywordIds) {
    final extras = kKeywordToExtraGenres[id];
    if (extras == null) continue;
    for (final g in extras) {
      if (seen.add(g)) out.add(g);
    }
  }
  return out;
}

/// Maps TMDB keyword ids → sub-genre tag names. Parallel axis to
/// [kKeywordToExtraGenres]: instead of widening canonical Genre names,
/// this layer tags titles with narrower flavour labels ("wildlife",
/// "true_crime", "slasher", …) that the user can multi-select on Home as
/// a filter parallel to genres.
///
/// Semantics: AND-intersection within sub-genres AND between Genre and
/// sub-genres — exactly like the Genre filter (see CLAUDE.md gotcha 10).
/// Selecting Genre=Documentary + Sub-topic=wildlife returns titles whose
/// canonical genres contain Documentary AND whose sub-genre set contains
/// wildlife. Empty selection on either axis = no constraint on that axis.
///
/// Tags are snake_case internal keys; the UI maps them to human-readable
/// labels (e.g. "wildlife" → "Animal docs"). Multiple keyword ids can
/// share a tag — every keyword that reliably implies "wildlife" maps to
/// the same `wildlife` string, so any one of them widens the title's tag
/// set. Tags do NOT need to match canonical genre names.
///
/// Keys verified against TMDB `/search/keyword` on 2026-05-23; regenerate
/// via `scripts/generate_keyword_subgenre_map.py` when adding new tags.
/// Drop any tag whose keyword ids you can't verify — don't ship a
/// sub-genre that maps to keywords TMDB doesn't actually use.
const Map<int, Set<String>> kKeywordToSubgenres = <int, Set<String>>{
  // ── wildlife (Animal docs) ──
  9902: {'wildlife'},
  18165: {'wildlife'},
  18330: {'wildlife'},
  221355: {'wildlife'},
  324404: {'wildlife'},
  361118: {'wildlife'},
  // ── true_crime (True crime) ──
  33722: {'true_crime'},
  // ── music_doc (Music docs) ──
  33899: {'music_doc'},
  156205: {'music_doc'},
  246377: {'music_doc'},
  // ── history_doc (History docs) ──
  321490: {'history_doc'},
  // ── science_tech (Science & tech) ──
  1576: {'science_tech'},
  191132: {'science_tech'},
  287067: {'science_tech'},
  325892: {'science_tech'},
  // ── sport_doc (Sports docs) ──
  159290: {'sport_doc'},
  // ── food_doc (Food & cooking) ──
  1918: {'food_doc'},
  10637: {'food_doc'},
  18293: {'food_doc'},
  368072: {'food_doc'},
  // ── travel_doc (Travel docs) ──
  9935: {'travel_doc'},
  // ── political_doc (Political docs) ──
  6078: {'political_doc'},
  264792: {'political_doc'},
  // ── environmental_doc (Climate & nature) ──
  2210: {'environmental_doc'},
  33577: {'environmental_doc'},
  156388: {'environmental_doc'},
  // ── slasher (Slasher) ──
  12339: {'slasher'},
  // ── found_footage (Found footage) ──
  163053: {'found_footage'},
  // ── psychological_horror (Psychological horror) ──
  295907: {'psychological_horror'},
  // ── cosmic_horror (Cosmic horror) ──
  215959: {'cosmic_horror'},
  // ── vampire (Vampire) ──
  3133: {'vampire'},
  // ── zombie (Zombie) ──
  12377: {'zombie'},
  // ── body_horror (Body horror) ──
  283085: {'body_horror'},
  // ── supernatural (Supernatural) ──
  6152: {'supernatural'},
  // ── gothic (Gothic) ──
  33505: {'gothic'},
  // ── monster (Monster) ──
  1299: {'monster'},
  // ── demonic (Demonic / possession) ──
  2626: {'demonic'},
  161261: {'demonic'},
  // ── witchcraft (Witchcraft / occult) ──
  616: {'witchcraft'},
  40931: {'witchcraft'},
  156174: {'witchcraft'},
  // ── cyberpunk (Cyberpunk) ──
  12190: {'cyberpunk'},
  // ── space_opera (Space opera) ──
  161176: {'space_opera'},
  // ── kaiju (Kaiju) ──
  161791: {'kaiju'},
  // ── time_travel (Time travel) ──
  4379: {'time_travel'},
  // ── dystopia (Dystopia) ──
  4565: {'dystopia'},
  // ── post_apocalyptic (Post-apocalyptic) ──
  4458: {'post_apocalyptic'},
  // ── alien_invasion (Alien invasion) ──
  14909: {'alien_invasion'},
  // ── artificial_intelligence (AI / robots) ──
  14544: {'artificial_intelligence'},
  371846: {'artificial_intelligence'},
  // ── virtual_reality (Virtual reality) ──
  4563: {'virtual_reality'},
  // ── heist (Heist) ──
  10051: {'heist'},
  // ── mafia (Mafia / mob) ──
  10391: {'mafia'},
  231149: {'mafia'},
  // ── detective (Detective / noir) ──
  703: {'detective'},
  155790: {'detective'},
  207268: {'detective'},
  // ── gangster (Gangster) ──
  3149: {'gangster'},
  // ── drug_trade (Drug trade / cartel) ──
  2149: {'drug_trade'},
  10175: {'drug_trade'},
  // ── prison (Prison) ──
  378: {'prison'},
  // ── serial_killer (Serial killer) ──
  10714: {'serial_killer'},
  // ── undercover (Undercover) ──
  1568: {'undercover'},
  // ── hitman (Hitman / assassin) ──
  782: {'hitman'},
  2708: {'hitman'},
  // ── martial_arts (Martial arts) ──
  779: {'martial_arts'},
  780: {'martial_arts'},
  // ── spy (Spy / espionage) ──
  470: {'spy'},
  5265: {'spy'},
  // ── military (Military) ──
  162365: {'military'},
  // ── superhero (Superhero) ──
  9715: {'superhero'},
  // ── dark_comedy (Dark comedy) ──
  10123: {'dark_comedy'},
  373401: {'dark_comedy'},
  // ── romcom (Romantic comedy) ──
  375047: {'romcom'},
  // ── satire (Satire) ──
  8201: {'satire'},
  // ── mockumentary (Mockumentary) ──
  11800: {'mockumentary'},
  // ── slapstick (Slapstick) ──
  364753: {'slapstick'},
  // ── courtroom (Courtroom / legal) ──
  33519: {'courtroom'},
  214780: {'courtroom'},
  // ── coming_of_age (Coming of age) ──
  10683: {'coming_of_age'},
  // ── period_drama (Period drama) ──
  15060: {'period_drama'},
  // ── biopic (Biopic) ──
  5565: {'biopic'},
  360939: {'biopic'},
  // ── high_fantasy (High fantasy) ──
  211227: {'high_fantasy'},
  // ── dark_fantasy (Dark fantasy) ──
  177895: {'dark_fantasy'},
  // ── fairy_tale (Fairy tale) ──
  3205: {'fairy_tale'},
  // ── psychological_thriller (Psychological thriller) ──
  12565: {'psychological_thriller'},
  // ── political_thriller (Political thriller) ──
  209817: {'political_thriller'},
  // ── conspiracy (Conspiracy) ──
  10410: {'conspiracy'},
  // ── neo_western (Neo-western) ──
  168713: {'neo_western'},
  // ── spaghetti_western (Spaghetti western) ──
  156212: {'spaghetti_western'},
  // ── wwii (WWII) ──
  1956: {'wwii'},
  // ── vietnam_war (Vietnam war) ──
  2957: {'vietnam_war'},
  // ── whodunit (Whodunit) ──
  12570: {'whodunit'},
  // ── treasure_hunt (Treasure hunt) ──
  6956: {'treasure_hunt'},
  // ── exploration (Exploration) ──
  4759: {'exploration'},
  // ── musical (Musical) ──
  4344: {'musical'},
  // ── anime (Anime) ──
  210024: {'anime'},
  // ── stop_motion (Stop motion) ──
  10121: {'stop_motion'},
  // ── ancient_history (Ancient history) ──
  5049: {'ancient_history'},
  157894: {'ancient_history'},
  162861: {'ancient_history'},
  // ── medieval (Medieval) ──
  161257: {'medieval'},
};

/// Parent canonical genre(s) each sub-genre is a narrowing of. Used by
/// the Home filter panel to render contextual chip lists: a sub-topic
/// chip is shown only when at least one of its parents is in the user's
/// selected Genre set (or the sub-topic is already selected, so the user
/// can deselect it). Picking "Animal docs" without Documentary selected
/// is incoherent — Animal docs is a narrowing of Documentary, not a
/// parallel filter.
///
/// Parent matching is synonym-aware via [genreMatches] in tmdb_genres.dart
/// — declaring `'cyberpunk': {'Science Fiction'}` covers the TV variant
/// `'Sci-Fi & Fantasy'` automatically. Don't double-list synonyms here.
const Map<String, Set<String>> kSubgenreParents = <String, Set<String>>{
  'wildlife': {'Documentary'},
  'true_crime': {'Documentary', 'Crime'},
  'music_doc': {'Documentary', 'Music'},
  'history_doc': {'Documentary', 'History'},
  'science_tech': {'Documentary'},
  'sport_doc': {'Documentary'},
  'food_doc': {'Documentary'},
  'travel_doc': {'Documentary'},
  'political_doc': {'Documentary'},
  'environmental_doc': {'Documentary'},
  'slasher': {'Horror'},
  'found_footage': {'Horror'},
  'psychological_horror': {'Horror'},
  'cosmic_horror': {'Horror'},
  'vampire': {'Horror'},
  'zombie': {'Horror'},
  'body_horror': {'Horror'},
  'supernatural': {'Horror'},
  'gothic': {'Horror'},
  'monster': {'Horror'},
  'demonic': {'Horror'},
  'witchcraft': {'Horror'},
  'cyberpunk': {'Science Fiction'},
  'space_opera': {'Science Fiction'},
  'kaiju': {'Science Fiction'},
  'time_travel': {'Science Fiction'},
  'dystopia': {'Science Fiction'},
  'post_apocalyptic': {'Science Fiction'},
  'alien_invasion': {'Science Fiction'},
  'artificial_intelligence': {'Science Fiction'},
  'virtual_reality': {'Science Fiction'},
  'heist': {'Crime'},
  'mafia': {'Crime'},
  'detective': {'Crime', 'Mystery'},
  'gangster': {'Crime'},
  'drug_trade': {'Crime'},
  'prison': {'Crime'},
  'serial_killer': {'Crime', 'Thriller'},
  'undercover': {'Crime'},
  'hitman': {'Crime', 'Action'},
  'martial_arts': {'Action'},
  'spy': {'Action', 'Thriller'},
  'military': {'Action', 'War'},
  'superhero': {'Action'},
  'dark_comedy': {'Comedy'},
  'romcom': {'Comedy', 'Romance'},
  'satire': {'Comedy'},
  'mockumentary': {'Comedy'},
  'slapstick': {'Comedy'},
  'courtroom': {'Drama'},
  'coming_of_age': {'Drama'},
  'period_drama': {'Drama'},
  'biopic': {'Drama'},
  'high_fantasy': {'Fantasy'},
  'dark_fantasy': {'Fantasy'},
  'fairy_tale': {'Fantasy', 'Family'},
  'psychological_thriller': {'Thriller'},
  'political_thriller': {'Thriller'},
  'conspiracy': {'Thriller'},
  'neo_western': {'Western'},
  'spaghetti_western': {'Western'},
  'wwii': {'War'},
  'vietnam_war': {'War'},
  'whodunit': {'Mystery'},
  'treasure_hunt': {'Adventure'},
  'exploration': {'Adventure'},
  'musical': {'Music'},
  'anime': {'Animation'},
  'stop_motion': {'Animation'},
  'ancient_history': {'History'},
  'medieval': {'History'},
};

/// Returns a sub-genre set combining [currentSubgenres] with any tags
/// implied by [keywordIds] per [kKeywordToSubgenres]. Mirrors
/// [augmentGenresWithKeywords] but for the parallel sub-genre axis.
///
/// Pure / additive — never removes existing tags. Unknown keyword ids
/// are silently skipped. Empty inputs return an empty set.
Set<String> augmentSubgenresWithKeywords(
  Iterable<String> currentSubgenres,
  Iterable<int> keywordIds,
) {
  final out = <String>{};
  for (final s in currentSubgenres) {
    if (s.isEmpty) continue;
    out.add(s);
  }
  for (final id in keywordIds) {
    final extras = kKeywordToSubgenres[id];
    if (extras == null) continue;
    out.addAll(extras);
  }
  return out;
}

/// Returns true when [recSubgenres] satisfies every tag in
/// [selectedSubgenres]. Empty [selectedSubgenres] always matches (no
/// filter). AND-intersection semantics — same contract as the Genre
/// filter (gotcha 10): a rec with empty `subgenres` drops out under any
/// non-empty selection because "tagged with all of these" can't be
/// verified for an empty tag set.
bool subgenreMatches(
  Set<String> recSubgenres,
  Set<String> selectedSubgenres,
) {
  if (selectedSubgenres.isEmpty) return true;
  for (final s in selectedSubgenres) {
    if (!recSubgenres.contains(s)) return false;
  }
  return true;
}

/// Human-readable display label for a sub-genre tag (snake_case → Title
/// Case with friendly variants). Used by the Home filter panel's
/// Sub-topics section so chips read as "Animal docs", "True crime", etc.
/// Unknown tags fall back to a Title-Case rendering of the key.
String subgenreLabel(String tag) => switch (tag) {
      'wildlife' => 'Animal docs',
      'true_crime' => 'True crime',
      'music_doc' => 'Music docs',
      'history_doc' => 'History docs',
      'science_tech' => 'Science & tech',
      'sport_doc' => 'Sports docs',
      'food_doc' => 'Food & cooking',
      'travel_doc' => 'Travel docs',
      'political_doc' => 'Political docs',
      'environmental_doc' => 'Climate & nature',
      'slasher' => 'Slasher',
      'found_footage' => 'Found footage',
      'psychological_horror' => 'Psychological horror',
      'cosmic_horror' => 'Cosmic horror',
      'vampire' => 'Vampire',
      'zombie' => 'Zombie',
      'body_horror' => 'Body horror',
      'supernatural' => 'Supernatural',
      'gothic' => 'Gothic',
      'monster' => 'Monster',
      'demonic' => 'Demonic / possession',
      'witchcraft' => 'Witchcraft / occult',
      'cyberpunk' => 'Cyberpunk',
      'space_opera' => 'Space opera',
      'kaiju' => 'Kaiju',
      'time_travel' => 'Time travel',
      'dystopia' => 'Dystopia',
      'post_apocalyptic' => 'Post-apocalyptic',
      'alien_invasion' => 'Alien invasion',
      'artificial_intelligence' => 'AI / robots',
      'virtual_reality' => 'Virtual reality',
      'heist' => 'Heist',
      'mafia' => 'Mafia / mob',
      'detective' => 'Detective / noir',
      'gangster' => 'Gangster',
      'drug_trade' => 'Drug trade / cartel',
      'prison' => 'Prison',
      'serial_killer' => 'Serial killer',
      'undercover' => 'Undercover',
      'hitman' => 'Hitman / assassin',
      'martial_arts' => 'Martial arts',
      'spy' => 'Spy / espionage',
      'military' => 'Military',
      'superhero' => 'Superhero',
      'dark_comedy' => 'Dark comedy',
      'romcom' => 'Romantic comedy',
      'satire' => 'Satire',
      'mockumentary' => 'Mockumentary',
      'slapstick' => 'Slapstick',
      'courtroom' => 'Courtroom / legal',
      'coming_of_age' => 'Coming of age',
      'period_drama' => 'Period drama',
      'biopic' => 'Biopic',
      'high_fantasy' => 'High fantasy',
      'dark_fantasy' => 'Dark fantasy',
      'fairy_tale' => 'Fairy tale',
      'psychological_thriller' => 'Psychological thriller',
      'political_thriller' => 'Political thriller',
      'conspiracy' => 'Conspiracy',
      'neo_western' => 'Neo-western',
      'spaghetti_western' => 'Spaghetti western',
      'wwii' => 'WWII',
      'vietnam_war' => 'Vietnam war',
      'whodunit' => 'Whodunit',
      'treasure_hunt' => 'Treasure hunt',
      'exploration' => 'Exploration',
      'musical' => 'Musical',
      'anime' => 'Anime',
      'stop_motion' => 'Stop motion',
      'ancient_history' => 'Ancient history',
      'medieval' => 'Medieval',
      _ => tag
          .split('_')
          .map((w) => w.isEmpty ? w : '${w[0].toUpperCase()}${w.substring(1)}')
          .join(' '),
    };

/// The full set of known sub-genre tags, alphabetised by display label.
/// Source of truth for tests; the Home filter panel renders a CONTEXTUAL
/// subset via [visibleSubgenresFor] driven by the user's selected Genre
/// set.
List<String> get kAllSubgenres {
  final set = <String>{};
  for (final tags in kKeywordToSubgenres.values) {
    set.addAll(tags);
  }
  final list = set.toList();
  list.sort((a, b) => subgenreLabel(a).compareTo(subgenreLabel(b)));
  return List.unmodifiable(list);
}

/// Inverse map: sub-genre tag → TMDB keyword ids that imply it. Used by
/// the discover-pool augmentation path so when a user selects sub-genre
/// filters, the refresh's `/discover` call can OR-pipe the relevant
/// keyword ids in `with_keywords` to seed the pool with sub-genre-
/// relevant titles instead of relying purely on the client filter to
/// find them after the fact.
Map<String, Set<int>> get kSubgenreToKeywordIds {
  final out = <String, Set<int>>{};
  kKeywordToSubgenres.forEach((kid, tags) {
    for (final t in tags) {
      out.putIfAbsent(t, () => <int>{}).add(kid);
    }
  });
  return Map.unmodifiable(out);
}

/// Genres whose TV taxonomy is incomplete — augmenting the discover query
/// with these signature keywords pulls TV titles INTO the pool that would
/// otherwise be missed.
///
/// **Horror**: TMDB has no Horror genre id for TV (`/genre/tv/list` returns
/// nothing equivalent), so a refresh with just `Horror` selected fires
/// `with_genres=27` on the movie side and `with_genres=` (empty!) on the
/// TV side — TV horror shows like "The Haunting of Hill House" live as
/// `Drama` + `Sci-Fi & Fantasy` on TMDB and don't surface at all. Piping
/// the canonical horror keyword ids (slasher, vampire, zombie, cosmic
/// horror, supernatural, gothic, exorcism, witchcraft, …) into
/// `with_keywords` brings them into the pool; the existing keyword→genre
/// augmentation (gotcha 43) then stamps `Horror` on those rec docs so the
/// client-side AND filter passes them through. Without the boost, picking
/// just "Horror" returns ~7 movies and zero TV.
///
/// **Music**: same problem (no TV Music genre); skipped for now because
/// the user hasn't asked for it — add when it becomes a problem.
///
/// Composes with [kSubgenreToKeywordIds] via simple set union when both
/// genres and sub-topics are selected. No ordering required — TMDB
/// `with_keywords` is OR-semantics regardless of position.
const Map<String, Set<int>> kGenreBoostKeywords = <String, Set<int>>{
  'Horror': {
    // Mirror the horror sub-topic keyword ids so the discover pool catches
    // every TV horror flavour. Most of these also augment `genres` →
    // `{'Horror'}` via kKeywordToExtraGenres so the client-side filter
    // accepts the title after augmentation.
    12339, // slasher
    163053, // found footage
    295907, // psychological horror
    215959, // cosmic horror
    3133, // vampire
    12377, // zombie
    283085, // body horror
    6152, // supernatural
    33505, // gothic
    2626, // exorcism
    161261, // demonic possession
    40931, // witchcraft
  },
};
